/**
 * Member Validation Schemas
 * Input validation for member endpoints using Joi
 *
 * @module modules/members/memberValidation
 */

const Joi = require('joi');

/**
 * Create member validation schema (adapted to new structure)
 * Note: memberCode is auto-generated by the system and should not be provided
 */
const createMemberSchema = Joi.object({
    fullName: Joi.string()
        .trim()
        .min(3)
        .max(100)
        .required()
        .messages({
            'string.empty': 'Full name is required',
            'string.min': 'Full name must have at least 3 characters',
            'string.max': 'Full name cannot exceed 100 characters',
            'any.required': 'Full name is required'
        }),

    identification: Joi.string()
        .trim()
        .pattern(/^[0-9-]+$/)
        .required()
        .messages({
            'string.empty': 'Identification number is required',
            'string.pattern.base': 'Identification number can only contain numbers and hyphens',
            'any.required': 'Identification number is required'
        }),

    qualityId: Joi.number()
        .integer()
        .valid(1, 2)
        .required()
        .messages({
            'number.base': 'Member quality must be a number',
            'any.only': 'Quality must be 1 (Student) or 2 (Staff)',
            'any.required': 'Member quality is required'
        }),

    levelId: Joi.number()
        .integer()
        .min(1)
        .max(9)
        .optional()
        .allow(null)
        .messages({
            'number.base': 'Level must be a number',
            'number.min': 'Level must be greater than or equal to 1',
            'number.max': 'Level must be less than or equal to 9'
        }),

    gender: Joi.string()
        .trim()
        .valid('M', 'F')
        .optional()
        .allow('', null)
        .messages({
            'any.only': 'Gender must be M (Male) or F (Female)'
        }),

    institutionalEmail: Joi.string()
        .trim()
        .email()
        .optional()
        .allow('', null)
        .messages({
            'string.email': 'Institutional email must be valid'
        }),

    photoUrl: Joi.string()
        .uri()
        .optional()
        .allow('', null)
        .messages({
            'string.uri': 'Photo URL must be valid'
        })
});

/**
 * Update member validation schema (adapted to new structure)
 * All fields are optional for updates
 * Note: memberCode cannot be updated as it's auto-generated
 */
const updateMemberSchema = Joi.object({
    fullName: Joi.string()
        .trim()
        .min(3)
        .max(100)
        .optional()
        .messages({
            'string.min': 'Full name must have at least 3 characters',
            'string.max': 'Full name cannot exceed 100 characters'
        }),

    identification: Joi.string()
        .trim()
        .pattern(/^[0-9-]+$/)
        .optional()
        .messages({
            'string.pattern.base': 'Identification number can only contain numbers and hyphens'
        }),

    qualityId: Joi.number()
        .integer()
        .valid(1, 2)
        .optional()
        .messages({
            'number.base': 'Member quality must be a number',
            'any.only': 'Quality must be 1 (Student) or 2 (Staff)'
        }),

    levelId: Joi.number()
        .integer()
        .min(1)
        .max(9)
        .optional()
        .allow(null)
        .messages({
            'number.base': 'Level must be a number',
            'number.min': 'Level must be greater than or equal to 1',
            'number.max': 'Level must be less than or equal to 9'
        }),

    gender: Joi.string()
        .trim()
        .valid('M', 'F')
        .optional()
        .allow('', null)
        .messages({
            'any.only': 'Gender must be M (Male) or F (Female)'
        }),

    institutionalEmail: Joi.string()
        .trim()
        .email()
        .optional()
        .allow('', null)
        .messages({
            'string.email': 'Institutional email must be valid'
        }),

    photoUrl: Joi.string()
        .uri()
        .optional()
        .allow('', null)
        .messages({
            'string.uri': 'Photo URL must be valid'
        }),

    isActive: Joi.boolean()
        .optional()
        .messages({
            'boolean.base': 'isActive must be a boolean value'
        })
}).min(1);

/**
 * Batch QR generation validation schema
 */
const batchQrSchema = Joi.object({
    memberIds: Joi.array()
        .items(Joi.number().integer().positive())
        .min(1)
        .required()
        .messages({
            'array.base': 'memberIds must be an array',
            'array.min': 'At least one member ID must be provided',
            'any.required': 'memberIds is required'
        })
});

/**
 * Verify QR validation schema
 */
const verifyQrSchema = Joi.object({
    qrHash: Joi.string()
        .trim()
        .required()
        .messages({
            'string.empty': 'QR code hash is required',
            'any.required': 'QR code hash is required'
        })
});

module.exports = {
    createMemberSchema,
    updateMemberSchema,
    batchQrSchema,
    verifyQrSchema
};
