/**
 * Member Validation Schemas
 * Input validation for member endpoints using Joi
 *
 * @module modules/members/memberValidation
 */

const Joi = require('joi');

/**
 * Create member validation schema (adapted to new structure)
 * Note: memberCode is auto-generated by the system and should not be provided
 */
const createMemberSchema = Joi.object({
    fullName: Joi.string()
        .trim()
        .min(3)
        .max(100)
        .required()
        .messages({
            'string.empty': 'El nombre completo es requerido',
            'string.min': 'El nombre completo debe tener al menos 3 caracteres',
            'string.max': 'El nombre completo no puede exceder 100 caracteres',
            'any.required': 'El nombre completo es requerido'
        }),

    identification: Joi.string()
        .trim()
        .pattern(/^[0-9-]+$/)
        .required()
        .messages({
            'string.empty': 'El número de identificación es requerido',
            'string.pattern.base': 'El número de identificación solo puede contener números y guiones',
            'any.required': 'El número de identificación es requerido'
        }),

    qualityId: Joi.number()
        .integer()
        .valid(1, 2)
        .required()
        .messages({
            'number.base': 'La calidad del miembro debe ser un número',
            'any.only': 'La calidad debe ser 1 (Estudiante) o 2 (Funcionario)',
            'any.required': 'La calidad del miembro es requerida'
        }),

    levelId: Joi.number()
        .integer()
        .min(1)
        .max(9)
        .optional()
        .allow(null)
        .messages({
            'number.base': 'El nivel debe ser un número',
            'number.min': 'El nivel debe ser mayor o igual a 1',
            'number.max': 'El nivel debe ser menor o igual a 9'
        }),

    gender: Joi.string()
        .trim()
        .valid('M', 'F')
        .optional()
        .allow('', null)
        .messages({
            'any.only': 'El género debe ser M (Masculino) o F (Femenino)'
        }),

    institutionalEmail: Joi.string()
        .trim()
        .email()
        .optional()
        .allow('', null)
        .messages({
            'string.email': 'El correo institucional debe ser válido'
        }),

    photoUrl: Joi.string()
        .uri()
        .optional()
        .allow('', null)
        .messages({
            'string.uri': 'La URL de la foto debe ser válida'
        })
});

/**
 * Update member validation schema (adapted to new structure)
 * All fields are optional for updates
 * Note: memberCode cannot be updated as it's auto-generated
 */
const updateMemberSchema = Joi.object({
    fullName: Joi.string()
        .trim()
        .min(3)
        .max(100)
        .optional()
        .messages({
            'string.min': 'El nombre completo debe tener al menos 3 caracteres',
            'string.max': 'El nombre completo no puede exceder 100 caracteres'
        }),

    identification: Joi.string()
        .trim()
        .pattern(/^[0-9-]+$/)
        .optional()
        .messages({
            'string.pattern.base': 'El número de identificación solo puede contener números y guiones'
        }),

    qualityId: Joi.number()
        .integer()
        .valid(1, 2)
        .optional()
        .messages({
            'number.base': 'La calidad del miembro debe ser un número',
            'any.only': 'La calidad debe ser 1 (Estudiante) o 2 (Funcionario)'
        }),

    levelId: Joi.number()
        .integer()
        .min(1)
        .max(9)
        .optional()
        .allow(null)
        .messages({
            'number.base': 'El nivel debe ser un número',
            'number.min': 'El nivel debe ser mayor o igual a 1',
            'number.max': 'El nivel debe ser menor o igual a 9'
        }),

    gender: Joi.string()
        .trim()
        .valid('M', 'F')
        .optional()
        .allow('', null)
        .messages({
            'any.only': 'El género debe ser M (Masculino) o F (Femenino)'
        }),

    institutionalEmail: Joi.string()
        .trim()
        .email()
        .optional()
        .allow('', null)
        .messages({
            'string.email': 'El correo institucional debe ser válido'
        }),

    photoUrl: Joi.string()
        .uri()
        .optional()
        .allow('', null)
        .messages({
            'string.uri': 'La URL de la foto debe ser válida'
        }),

    isActive: Joi.boolean()
        .optional()
        .messages({
            'boolean.base': 'isActive debe ser un valor booleano'
        })
}).min(1);

/**
 * Batch QR generation validation schema
 */
const batchQrSchema = Joi.object({
    memberIds: Joi.array()
        .items(Joi.number().integer().positive())
        .min(1)
        .required()
        .messages({
            'array.base': 'memberIds debe ser un array',
            'array.min': 'Debe proporcionar al menos un ID de miembro',
            'any.required': 'memberIds es requerido'
        })
});

/**
 * Verify QR validation schema
 */
const verifyQrSchema = Joi.object({
    qrHash: Joi.string()
        .trim()
        .required()
        .messages({
            'string.empty': 'El hash del código QR es requerido',
            'any.required': 'El hash del código QR es requerido'
        })
});

module.exports = {
    createMemberSchema,
    updateMemberSchema,
    batchQrSchema,
    verifyQrSchema
};
