/**
 * Error Codes Constants
 */

const ERROR_CODES = {
    // Authentication errors
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_INVALID: 'TOKEN_INVALID',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',

    // User errors
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    USER_INACTIVE: 'USER_INACTIVE',

    // Member errors
    MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
    MEMBER_ALREADY_EXISTS: 'MEMBER_ALREADY_EXISTS',
    MEMBER_INACTIVE: 'MEMBER_INACTIVE',
    INVALID_QR_CODE: 'INVALID_QR_CODE',

    // Assembly errors
    ASSEMBLY_NOT_FOUND: 'ASSEMBLY_NOT_FOUND',
    NO_ACTIVE_ASSEMBLY: 'NO_ACTIVE_ASSEMBLY',
    ASSEMBLY_ALREADY_ACTIVE: 'ASSEMBLY_ALREADY_ACTIVE',

    // Attendance errors
    ATTENDANCE_ALREADY_REGISTERED: 'ATTENDANCE_ALREADY_REGISTERED',
    ATTENDANCE_NOT_FOUND: 'ATTENDANCE_NOT_FOUND',

    // Validation errors
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_INPUT: 'INVALID_INPUT',

    // Database errors
    DATABASE_ERROR: 'DATABASE_ERROR',
    QUERY_FAILED: 'QUERY_FAILED',

    // General errors
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    BAD_REQUEST: 'BAD_REQUEST'
};

module.exports = ERROR_CODES;